## One-hot Vector

A one-hot vector for an integer $n$ is a vector that has a one in its $n$-th slot, and zeros in all other slots. One-hot vectors are commonly used to represent categorical variables in machine learning models.

For example, given a list `[1, 4, 3, 2]` of integers, your function should produce the tensor:

```
[[0 1 0 0 0],
 [0 0 0 0 1],
 [0 0 0 1 0],
 [0 0 1 0 0]]
```

## View
As a convenience, calls to `.view()` may include a single **-1** argument; this puts enough elements on that dimension so that the output has the same number of elements as the input. This makes it easy to write some reshape operations in a way that is agnostic to the shape of the tensor

## Tensor类型转化
.item()
.int()/.float()

torch.tensor([List])

## Tensor的连接
- torch.cat
- torch.stack

注意参数是Tensor的列表(Sequence of Tensors)

### Challenges

.sort() 可以对按照指定的维度对张量中的元素进行排序

torch.nn.utils.rnn.pad_sequence() 填充一系列可变长度的tensor，把它们填充到等长

### Tip

The easiest way to remember is to think about the shapes of the tensors involved.
After summing with `dim=d`, the dimension at index `d` of the input is **eliminated** from the shape of the output tensor:

this is same for `min` or `max`